### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by emartynov** [paypal/paypal-android#147]
### PayPal Android SDK Version

0.0.9

### Environment

Sandbox

### Android Version & Device

Emulator

### PayPal dependencies

paypal-payments-sdk="com.paypal.android:paypal-native-payments:0.0.9"

### Describe the bug

Stacktrace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{se.doktor.doktorde.debug/com.paypal.pyplcheckout.ui.feature.home.activities.PYPLHomeActivity}: java.lang.IllegalStateException: Required value was null.
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.IllegalStateException: Required value was null.
                                                                                                    	at com.paypal.pyplcheckout.di.SdkComponent$Companion.getInstance(SdkComponent.kt:163)
                                                                                                    	at com.paypal.pyplcheckout.di.SdkComponentKt.inject(SdkComponent.kt:184)
                                                                                                    	at com.paypal.pyplcheckout.ui.feature.home.fragments.BaseFragment.onAttach(BaseFragment.kt:140)
                                                                                                    	at com.paypal.pyplcheckout.ui.feature.home.fragments.HomeFragment.onAttach(HomeFragment.kt:138)
                                                                                                    	at androidx.fragment.app.Fragment.performAttach(Fragment.java:3072)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1435)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2979)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2886)
                                                                                                    	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:220)
                                                                                                    	at com.paypal.pyplcheckout.ui.feature.home.activities.BaseActivity.onCreate(BaseActivity.kt:72)
                                                                                                    	at com.paypal.pyplcheckout.ui.feature.home.activities.PYPLHomeActivity.onCreate(PYPLHomeActivity.kt:104)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8305)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8284)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

### To reproduce

1. Integrate SDK
2. Launch payment on emulator and see browser screen
3. Press cross in toolbar
4. App crashes

### Expected behavior

1. Browser screen is closed

**Comment by sshropshire** [comment]
Hi @emartynov would you mind providing a video reproducing the issue so I can forward it to the appropriate team?

**Comment by emartynov** [comment]
Unfortunately, I can not reproduce it now. So most probably low priority.
