### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by emartynov** [paypal/paypal-android#164]
### PayPal Android SDK Version

0.0.10

### Environment

Sandbox

### PayPal dependencies

paypal-payments-sdk = "com.paypal.android:paypal-native-payments:0.0.10"

### Describe the bug

Crash

```
Fatal Exception: java.lang.NullPointerException: config.checkoutBaseActivity must not be null
       at com.paypal.pyplcheckout.ui.utils.PYPLCheckoutUtils.fallBackToWeb(PYPLCheckoutUtils.kt:387)
       at com.paypal.pyplcheckout.ui.utils.PYPLCheckoutUtils.fallbackIndefinite(PYPLCheckoutUtils.kt:349)
       at com.paypal.pyplcheckout.ui.utils.PYPLCheckoutUtils.fallBack(PYPLCheckoutUtils.kt:315)
       at com.paypal.pyplcheckout.ui.feature.home.viewmodel.MainPaysheetViewModel.proceedToLogin(MainPaysheetViewModel.java:662)
       at com.paypal.pyplcheckout.data.repositories.featureflag.Elmo$setup$1.invokeSuspend(Elmo.kt:76)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

From the stack trace it looks like the issue in the checkout SDK.

### To reproduce

Start checkout

### Expected behavior

Not crash

**Comment by emartynov** [comment]
Could also be related to that native API doesn't require activity context but the app context (which I prefer more).

**Comment by emartynov** [comment]
I don't see it anymore.
